[package]
name = "nsz-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "nsz_rs"
path = "src/lib.rs"

[dependencies]
thiserror = "2"
zstd = { version = "0.13", features = ["zstdmt"] }
aes = "0.8"
ctr = "0.9"
sha2 = "0.10"
